name: npm package

on:
    release:
        types: [created]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - run: echo "PACKAGE_JSON=$(jq -c . < package.json)" >> $GITHUB_ENV
            - uses: pnpm/action-setup@v6
            - uses: actions/setup-node@v6
              with:
                node-version: ${{ fromJson(env.PACKAGE_JSON).volta.node }}
                registry-url: https://registry.npmjs.org/
                cach: pnpm
            - name: Upgrade npm for OCID support
              run: npm i -g npm@latest
            - run: pnpm install --frozen-lockfile
            - run: pnpm clean
            - run: pnpm build
            - run: pnpm -r publish --provenance --access public --no-git-checks
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}